TravelApp.Web/Controllers/PastTravelsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TravelApp.Service.Implementation;
using TravelApp.Service.Interface;

namespace TravelApp.Web.Controllers
{
    public class PastTravelsController : Controller
    {
        private readonly IPastTravelsService _pastTravelsService;

        public PastTravelsController(IPastTravelsService pastTravelsService)
        {
            _pastTravelsService = pastTravelsService;
        }
        public IActionResult Index()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return View(_pastTravelsService.GetUserPastTravelsObjects(userId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddToPastTravels(Guid travelId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return Unauthorized();

            _pastTravelsService.AddToPastTravels(travelId, userId);

            return RedirectToAction("Index", "Travels");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveFromPastTravels(Guid travelId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return Unauthorized();

            _pastTravelsService.RemoveFromPastTravels(travelId, userId);

            return RedirectToAction("Index");
        }
    }
}

TravelApp.Web/Controllers/TravelsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TravelApp.Domain.DomainModels;
using TravelApp.Repository;
using TravelApp.Service.Implementation;
using TravelApp.Service.Interface;

namespace TravelApp.Web.Controllers
{
    public class TravelsController : Controller
    {
        private readonly ITravelService _travelService;
        private readonly ICityService _cityService;
        private readonly IWishlistService _wishlistService;
        private readonly IPastTravelsService _pastTravelsService;

        public TravelsController(ITravelService travelService, ICityService cityService, IWishlistService wishlistService, IPastTravelsService pastTravelsService)
        {
            _travelService = travelService;
            _cityService = cityService;
            _wishlistService = wishlistService;
            _pastTravelsService = pastTravelsService;
        }

        // GET: Travels
        public async Task<IActionResult> Index()
        {
            var travels = _travelService.GetAll();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var wishlistTravelIds = string.IsNullOrEmpty(userId)
                ? new List<Guid>()
                : _wishlistService.GetUserWishlist(userId).Select(w => w.TravelId).ToList();

            var pastTravelsIds = string.IsNullOrEmpty(userId)
                ? new List<Guid>()
                : _pastTravelsService.GetUserPastTravels(userId).Select(w => w.TravelId).ToList();

            ViewBag.WishlistTravelIds = wishlistTravelIds;
            ViewBag.PastTravelsIds = pastTravelsIds;

            return View(travels);
        }

        // GET: Travels/Details/5
         public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var travel = _travelService.GetById(id.Value);
            if (travel == null)
            {
                return NotFound();
            }
            var cities = _cityService.GetAll();
            ViewBag.Cities = new MultiSelectList(cities, "Id", "Name", travel.Cities?.Select(c => c.Id));
            return View(travel);
        }

        // GET: Travels/Create
        public IActionResult Create()
        {
            var cities = _cityService.GetAll();
            ViewBag.Cities = new MultiSelectList(cities, "Id", "Name");
            return View();
        }

        // POST: Travels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,StartDate,EndDate,Price,VisaNeeded,Id")] Travel travel, List<Guid> selectedCities)
        {
            if (ModelState.IsValid)
            {
                if (selectedCities != null && selectedCities.Any())
                {
                    var cities0 = _cityService.GetAll().Where(c => selectedCities.Contains(c.Id)).ToList();
                    travel.Cities = cities0;
                }
                _travelService.Add(travel);
                return RedirectToAction(nameof(Index));
            }
            var cities = _cityService.GetAll();
            ViewBag.Cities = new MultiSelectList(cities, "Id", "Name", selectedCities);
            return View(travel);
        }

        // GET: Travels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return NotFound();

            var travel = _travelService.GetById(id.Value);
            if (travel == null) return NotFound();

            var cities = _cityService.GetAll();
            var selected = travel.Cities?.Select(c => c.Id).ToList();

            ViewBag.Cities = new MultiSelectList(cities, "Id", "Name", selected);
            return View(travel);
        }

        // POST: Travels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Title,Description,StartDate,EndDate,Price,VisaNeeded,Id")] Travel travel, List<Guid> selectedCities)
        {
            if (id != travel.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _travelService.Update(travel, selectedCities);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_travelService.GetById(travel.Id) == null)
                        return NotFound();
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }

            var cities = _cityService.GetAll();
            ViewBag.Cities = new MultiSelectList(cities, "Id", "Name", selectedCities);
            return View(travel);
        }
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travel = _travelService.GetById(id.Value);
            if (travel == null)
            {
                return NotFound();
            }

            var cities = _cityService.GetAll();
            ViewBag.Cities = new MultiSelectList(cities, "Id", "Name", travel.Cities?.Select(c => c.Id));

            return View(travel);
        }

        // POST: Travels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            _travelService.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }
        private bool TravelExists(Guid id)
        {
            return _travelService.GetById(id) == null ? false : true;
        }
    }
}

TravelApp.Web/Controllers/WishlistController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TravelApp.Service.Interface;

namespace TravelApp.Web.Controllers
{
    public class WishlistController : Controller
    {
        private readonly IWishlistService _wishlistService;

        public WishlistController(IWishlistService wishlistService)
        {
            _wishlistService = wishlistService;
        }
        public IActionResult Index()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return View(_wishlistService.GetUserWishlistTravels(userId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddToWishlist(Guid travelId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return Unauthorized();

            _wishlistService.AddToWishlist(travelId, userId);

            return RedirectToAction("Index", "Travels");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveFromWishlist(Guid travelId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return Unauthorized();

            _wishlistService.RemoveFromWishlist(travelId, userId);

            return RedirectToAction("Index");
        }
    }
}

TravelApp.Web/Views/Travels/Create.cshtml
@model TravelApp.Domain.DomainModels.Travel

@{
    ViewData["Title"] = "Create";
}

<h1>Create new Travels</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="VisaNeeded" /> @Html.DisplayNameFor(model => model.VisaNeeded)
                </label>
            </div>
            <div class="form-group">
                <label class="control-label">Cities</label>
                @Html.ListBox("selectedCities", (MultiSelectList)ViewBag.Cities, new { @class = "form-control" })
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Create" class="btn btn-success btn-sm" />
            </div>
        </form>
    </div>
</div>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TravelApp.Web/Views/Travels/Delete.cshtml
@model TravelApp.Domain.DomainModels.Travel

@{
    ViewData["Title"] = "Delete";
}

<h1>Travel Delete</h1>

<h3 class="text-danger">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VisaNeeded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VisaNeeded)
        </dd>
        <dt class="col-sm-2">Cities</dt>
        <dd class="col-sm-10">
            @if (Model.Cities != null && Model.Cities.Any())
            {
                <ul>
                    @foreach (var city in Model.Cities)
                    {
                        <li>@city.Name</li>
                    }
                </ul>
            }
            else
            {
                <span>No cities visited!</span>
            }
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> 
        <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
    </form>
</div>

TravelApp.Web/Views/Travels/Details.cshtml
@model TravelApp.Domain.DomainModels.Travel

@{
    ViewData["Title"] = "Details";
}

<h1>Travel Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VisaNeeded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VisaNeeded)
        </dd>
        <dt class="col-sm-2">Cities</dt>
        <dd class="col-sm-10">
            @if (Model.Cities != null && Model.Cities.Any())
            {
                <ul style="list-style-type: none;">
                    @foreach (var city in Model.Cities)
                    {
                        <li>@city.Name</li>
                    }
                </ul>
            }
            else
            {
                <span>No cities visited!</span>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning btn-sm">Edit</a> 
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>

TravelApp.Web/Views/Travels/Edit.cshtml
@model TravelApp.Domain.DomainModels.Travel

@{
    ViewData["Title"] = "Edit";
}

<h1>Travel Edit</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="VisaNeeded" /> @Html.DisplayNameFor(model => model.VisaNeeded)
                </label>
            </div>
            <div class="form-group">
                <label class="control-label">Cities Visited</label>
                @Html.ListBox("selectedCities", (MultiSelectList)ViewBag.Cities, new { @class = "form-control" })
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group mt-2">
                <input type="submit" value="Save" class="btn btn-success btn-sm" />
            </div>
        </form>
    </div>
</div>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TravelApp.Web/Views/Travels/Index.cshtml
@model IEnumerable<TravelApp.Domain.DomainModels.Travel>

@{
    ViewData["Title"] = "Index";
    var wishlistTravelIds = ViewBag.WishlistTravelIds as List<Guid> ?? new List<Guid>();
    var pastTravelIds = ViewBag.PastTravelsIds as List<Guid> ?? new List<Guid>();
}

<h1>Travels</h1>

<p>
    <a asp-action="Create" class="btn btn-dark btn-sm">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Price</th>
            <th>Visa Needed</th>
            <th>Cities Visited</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            bool isInWishlist = wishlistTravelIds.Contains(item.Id);
            bool isInPastTravels = pastTravelIds.Contains(item.Id);

            <tr>
                <td>@item.Title</td>
                <td>@item.Description</td>
                <td>@item.StartDate.ToShortDateString()</td>
                <td>@item.EndDate.ToShortDateString()</td>
                <td>@item.Price.ToString("C")</td>
                <td>@(item.VisaNeeded ? "Yes" : "No")</td>
                <td>
                    @if (item.Cities != null && item.Cities.Any())
                    {
                        @string.Join(", ", item.Cities.Select(c => c.Name))
                    }
                    else
                    {
                        <span>No cities!</span>
                    }
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm mb-1">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm mb-1">Details</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>

                </td>
                <td>
                    <form asp-controller="Wishlist" asp-action="AddToWishlist" method="post" style="display:inline">
                        <input type="hidden" name="travelId" value="@item.Id" />
                        <button type="submit" class="btn btn-dark btn-sm mb-1" @(isInPastTravels || isInWishlist ? "disabled" : "")>
                            @(isInWishlist ? "Already in Wishlist" : "Add to Wishlist")
                        </button>
                    </form>
                    <form asp-controller="PastTravels" asp-action="AddToPastTravels" method="post" style="display:inline">
                        <input type="hidden" name="travelId" value="@item.Id" />
                        <button type="submit" class="btn btn-dark btn-sm" @(isInPastTravels || isInWishlist ? "disabled" : "")>
                            @(isInPastTravels ? "Already in PastTravels" : "Add to PastTravels")
                        </button>
                    </form>
                </td>
               
            </tr>
        }
    </tbody>
</table>